### ISSUE TITLE
request_csi_frames working?

### ISSUE THREAD

**Issue by roger-** [jonathanmuller/ESP32-gather-channel-state-information-CSI-#11]
I can send null data packets successfully, but filtering ACK packets doesn't seem to work. Did you make any progress?

**Comment by jonathanmuller** [comment]
Hi, no progress on this unfortunately

**Comment by roger-** [comment]
Think I have it figured out.

I can currently send an NDP, filter out everything but ACKs, identify the correct one and capture the corresponding CSI data. This all happens in STA mode too, so communicating everything over WiFi is possible.

I still have to process the CSI and make sure it's correct, and currently the step of identifying the correct ACK wastes a lot of cycles (due to a missing ESP-IDF  API feature which is fortunately now in the development branch). I'll post some code in the future if anyone's interested.
