### ISSUE TITLE
Can clone/extract repo

### ISSUE THREAD

**Issue by JoaoSandrini** [jonathanmuller/ESP32-gather-channel-state-information-CSI-#12]
**Describe the bug**
Cant clone or extract the repo, ill link the errors below.

![image](https://github.com/user-attachments/assets/f235e8ed-6be6-424c-90d3-a8c2a58f8dc5)
![image](https://github.com/user-attachments/assets/b5a93210-8980-4983-81be-6be3b5a9c1ec)

**Comment by jonathanmuller** [comment]
Probably not linked to the repo but your OS or internet connection
