### ISSUE TITLE
"esp_event_loop.h" is obsolete in v4.0

### ISSUE THREAD

**Issue by BA8F0D39** [jonathanmuller/ESP32-gather-channel-state-information-CSI-#2]
I can't compile with ESP-IDF v4.0 and higher.

**Comment by jonathanmuller** [comment]
Did you find a way to adapt it ?
It should not be complicated as the CSI part of the code shouldn't have changed

**Comment by jonathanmuller** [comment]
Do you mind sharing the code ?
