### ISSUE TITLE
Add AGC info

### ISSUE THREAD

**Issue by fatihoezdemir** [jonathanmuller/ESP32-gather-channel-state-information-CSI-#3]
Hello, thanks for the project!
can you also add AGC info for each CSI Packet? 

Thank you

**Comment by jonathanmuller** [comment]
Hi, 

I'm not sure what you mean 
Like the gain of the AGC ?
Do you mind me asking what you would be using it for ?

Good day

**Comment by fatihoezdemir** [comment]
Hi,
I would like to perform indoor localization and want to get a power delay profile.
Yes, the AGC Gain
The Wi-fi receivers have an AGC gain, which distorts the amplitude.

**Comment by jonathanmuller** [comment]
Hi, 

I'm not sure we have a direct access to this, your best chance it to go through esp_wifi_set_csi_config -> manu_scale
Or maybe there is (hidden) function that allows this

You can try to disassemble the esp_wifi_set_csi_config function and see which calls are made, hopefully one to something like "AGC gain", but this doesn't seems straightforward
