### ISSUE TITLE
Constant sampling frequency

### ISSUE THREAD

**Issue by amirhb29** [jonathanmuller/ESP32-gather-channel-state-information-CSI-#4]
Hi,
Do you think it's possible to get CSI samples with a constant sampling frequency from ESP32?
ESP32 supports only passive collecting of CSI but the problem is that it does not offer an option to set a sampling frequency. Even the device itself collects CSI frames with non-constant dT.
And the sampling frequency is nearly 10 Hz. Have you been able to achieve better sampling frequency?

**Comment by jonathanmuller** [comment]
Hi, 

If you can provide me more context I may be able to give you a deeper answer.
From what I understand you look at the time each packet is received, and the time elapsed between packets is not always the same.

- What is the deviation from the (expected) fixed frequency ?
- Is the sender not sending frames at a fixed frequency or id the receiver not doing it ? (which one of the 2 is the less precise)
- I have not particularly tried, but how did you test do this : sending UDP packets from the client with 0 sleeping interval ?

Have a good day

**Comment by Geosearchef** [comment]
The TX rate is also limited by the serial connection, depending on how much you dump on that. I compacted the format a bit and still was only able to get ~10Hz out of it. In my tests, this was due to the serial connection.

Try increasing the baud rate to e.g. 921600.
```
#include "driver/uart.h"
void app_main()
{
	uart_set_baudrate(UART_NUM_0, UART_BAUD_RATE);
```

That allowed me to receive CSI for ~70-80 Hz. If you need more, you can increase it even a bit further, compact the CSI format to raw bytes instead of ASCII and maybe only transmit CSI for one training field instead of all of them.

**Comment by amirhb29** [comment]
> Hi,
> 
> If you can provide me more context I may be able to give you a deeper answer.
> From what I understand you look at the time each packet is received, and the time elapsed between packets is not always the same.
> 
> * What is the deviation from the (expected) fixed frequency ?
> * Is the sender not sending frames at a fixed frequency or id the receiver not doing it ? (which one of the 2 is the less precise)
> * I have not particularly tried, but how did you test do this : sending UDP packets from the client with 0 sleeping interval ?
> 
> Have a good day

Hi,
The time elapsed between two consecutive package is about 100 ms which gives a sampling frequency of around 10 Hz. Usually it changes from around 80 ms to 120 ms. I'm not using any UDP packet sending in my program. I've enabled the CSI with the information from this link:
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/wifi.html#wi-fi-channel-state-information

The ESP32 will connect to an access point and starts receiving CSI packets from it. I've tried connecting to another ESP32 instead of an access point but the sampling frequency was much lower. The problem is that 10 Hz is not enough to do some signal processing, the aliasing removes almost any data at a rate like 10 Hz. I have not seen any option or API to set a sampling frequency or even increase the rate somehow. I've tried raising the core frequency of ESP32 and removing other parts of my code but that did not improve the sampling frequency.

**Comment by amirhb29** [comment]
> The TX rate is also limited by the serial connection, depending on how much you dump on that. I compacted the format a bit and still was only able to get ~10Hz out of it. In my tests, this was due to the serial connection.
> 
> Try increasing the baud rate to e.g. 921600.
> 
> ```
> #include "driver/uart.h"
> void app_main()
> {
> 	uart_set_baudrate(UART_NUM_0, UART_BAUD_RATE);
> ```
> 
> That allowed me to receive CSI for ~70-80 Hz. If you need more, you can increase it even a bit further, compact the CSI format to raw bytes instead of ASCII and maybe only transmit CSI for one training field instead of all of them.

Hi,
I don't think it can be related to the serial connection. I'm using tick to calculate the time between each two packets. Also, I am using only one training field. Are you using the code on this repository and receiving 80 Hz CSI?

**Comment by Geosearchef** [comment]
> Are you using the code on this repository and receiving 80 Hz CSI?

Yes, I am. I'm now running at 100 Hz, can probably do a bit more. I set the serial baud rate as mentioned and additionally compressed the data format quite a bit. (I'm running two ESPs with active transmission though)

**Comment by amirhb29** [comment]
> > Are you using the code on this repository and receiving 80 Hz CSI?
> 
> Yes, I am. I'm now running at 100 Hz, can probably do a bit more. I set the serial baud rate as mentioned and additionally compressed the data format quite a bit. (I'm running two ESPs with active transmission though)

Thanks I will try that but still, I don't see how it's related to serial baud rate as I'm not using it at all. And the thing is using two ESPs will get me a much lower frequency than 10 Hz. I get 10 Hz from an access point which my ESPs will connect to.
Thanks again.
