### ISSUE TITLE
Can we obtain CSI data without null subcarriers.?

### ISSUE THREAD

**Issue by rtmtree** [jonathanmuller/ESP32-gather-channel-state-information-CSI-#6]
I just came into the repo and try to use "/create_STA_and_AP" to obtain the CSI data since I saw the example seems so good and contains no null in all 64 subcarriers at all.

![Figure_1](https://raw.githubusercontent.com/jonathanmuller/ESP32-gather-channel-state-information-CSI-/master/plot_csi_data/amplitude.png)
(from the "/plot_csi_data/amplitude.png" in the repo)

I wish I could have the CSI as good as the example . Then I ran "/create_STA_and_AP" on my 2 ESP32s as AP and STA.
And I got this.

![Figure_2](https://user-images.githubusercontent.com/36580295/110551036-5b66a400-8167-11eb-9cce-c50a81ede918.png)

(with filtered MAC and FIXED channel (8) )
Which seems different from the example.
If there are more secrets to obtain data as precise as the example. Please share .

Thank you in advance.

PS: I wanna get the perfect CSI for mapping to frequency domain to do the IFFT to turn it into Power delay profile.
If there is any suggestion on this , please share.

**Comment by jonathanmuller** [comment]
Hi, 

I got the frames in the example from real AP, not 2 ESP32 exchanging frames so that may explain the difference.
Your frame "1" look interesting. 
Can you verify the others are different (not exactly the same) ?

I expect that they are all exactly the same. If so it may be related to this bug : https://github.com/espressif/esp-idf/issues/2909


Also try to get more frames and see if you have other looking like the frame "1".

Also for the power delay profile all carrier frequency are explained here :
https://github.com/espressif/esp-idf/blob/master/docs/en/api-guides/wifi.rst under  "Wi-Fi Channel State Information"

**Comment by zhangyang428** [comment]
@jonathanmuller 
Hello,  thank you very much for your code,  but I have some problems when using it.
1. When I use the gather_csi_in_promiscuous demo,  I find that the target file displayed in CMakelists is scan. c， But the directory is only csi. c. 
2. Running the demo of the first file,  I can also get the phase diagram,  but how do I set up the code if I convert it to the amplitude diagram you're talking about? Can you provide a code use case for the amplitude diagram?
3. Do you have any suggestions for setting it to live display pictures? 
 
ps: My current chip is esp32s2. 

If possible, I hope to have more communication with you. 
Thank you in advance.

**Comment by jonathanmuller** [comment]
Hi, 

1. I moved some folder back and forth, so this should have slip through. Feel free to PR if you would rather have this cleaned on the source.
2. I may not have fully understood your question but assuming you are able to get the phase (which is atan2(imaginary part, real part)), then the amplitude is only sqrt((imaginary part)^2+(real part)^2)
3. The python program currently plot with plt.show(block=True), so you could put it to false in order not to block

Even if its a hassle, don't hesitate to take a look at the code I believe this would give you a clearer understanding of the way it works

**Comment by zhangyang428** [comment]
@jonathanmuller 
Hi，
    About the data collected:
![976c8a3c2b4f38f639389d05222442a](https://user-images.githubusercontent.com/72845894/111855794-946df800-8961-11eb-8b93-9aa399bd02b5.png)
    Do these data( the meaning of each number in the sequence ) have any specific implications?  Can it be converted into the data format collected with CSI-tools?

**Comment by kallu1294** [comment]
> I just came into the repo and try to use "/create_STA_and_AP" to obtain the CSI data since I saw the example seems so good and contains no null in all 64 subcarriers at all.
> 
> ![Figure_1](https://raw.githubusercontent.com/jonathanmuller/ESP32-gather-channel-state-information-CSI-/master/plot_csi_data/amplitude.png) (from the "/plot_csi_data/amplitude.png" in the repo)
> 
> I wish I could have the CSI as good as the example . Then I ran "/create_STA_and_AP" on my 2 ESP32s as AP and STA. And I got this.
> 
> ![Figure_2](https://user-images.githubusercontent.com/36580295/110551036-5b66a400-8167-11eb-9cce-c50a81ede918.png)
> 
> (with filtered MAC and FIXED channel (8) ) Which seems different from the example. If there are more secrets to obtain data as precise as the example. Please share .
> 
> Thank you in advance.
> 
> PS: I wanna get the perfect CSI for mapping to frequency domain to do the IFFT to turn it into Power delay profile. If there is any suggestion on this , please share.

sorry for asking silly question how can i get these graphs(wave forms)for amplitude and phase..??

**Comment by jonathanmuller** [comment]
@kallu1294 The question doesn't seem related to the initial thread, please stick to the "one question per thread" 
However :
- Run the code on the ESP32 (gather_csi_in_promiscuous)
- Use (modify) the provided python script with the port of your ESP32
