### ISSUE TITLE
Cloning fails

### ISSUE THREAD

**Issue by Tremito96** [jonathanmuller/ESP32-gather-channel-state-information-CSI-#7]
![image](https://user-images.githubusercontent.com/79624622/123887945-106bd900-d970-11eb-9041-fd964455cad3.png)
it gives this error when cloning, when i checked the promiscuous folder, it does not have a main folder. I tried downloading the zip file. when extracting it, that also gives the following error:
! C:\Users\Tremito\Downloads\Compressed\ESP32-gather-channel-state-information-CSI--master_2.zip: Cannot create folder C:\Users\Tremito\AppData\Local\Temp\Rar$DRa17352.22929\ESP32-gather-channel-state-information-CSI--master\gather_csi_in_promiscuous\build\include\config\smp\slave\con\params
  The system cannot find the path specified.
! C:\Users\Tremito\Downloads\Compressed\ESP32-gather-channel-state-information-CSI--master_2.zip: Cannot create folder C:\Users\Tremito\AppData\Local\Temp\Rar$DRa17352.22929\ESP32-gather-channel-state-information-CSI--master\gather_csi_in_promiscuous\build\include\config\smp\slave\con\params\upd
  The system cannot find the path specified.
! C:\Users\Tremito\Downloads\Compressed\ESP32-gather-channel-state-information-CSI--master_2.zip: Cannot create C:\Users\Tremito\AppData\Local\Temp\Rar$DRa17352.22929\ESP32-gather-channel-state-information-CSI--master\gather_csi_in_promiscuous\build\include\config\smp\slave\con\params\upd\enable.h
  The system cannot find the path specified.
! C:\Users\Tremito\Downloads\Compressed\ESP32-gather-channel-state-information-CSI--master_2.zip: Cannot create folder C:\Users\Tremito\AppData\Local\Temp\Rar$DRa17352.22929\ESP32-gather-channel-state-information-CSI--master\request_csi_frames\build\include\config\smp\slave\con\params
  The system cannot find the path specified.
! C:\Users\Tremito\Downloads\Compressed\ESP32-gather-channel-state-information-CSI--master_2.zip: Cannot create folder C:\Users\Tremito\AppData\Local\Temp\Rar$DRa17352.22929\ESP32-gather-channel-state-information-CSI--master\request_csi_frames\build\include\config\smp\slave\con\params\upd
  The system cannot find the path specified.
! C:\Users\Tremito\Downloads\Compressed\ESP32-gather-channel-state-information-CSI--master_2.zip: Cannot create C:\Users\Tremito\AppData\Local\Temp\Rar$DRa17352.22929\ESP32-gather-channel-state-information-CSI--master\request_csi_frames\build\include\config\smp\slave\con\params\upd\enable.h
  The system cannot find the path specified.
 
can someone help me with this?

**Comment by jonathanmuller** [comment]
It shouldn't matter as the build file will be overridden on the next compilation. Are you still able to build it ?

**Comment by Tremito96** [comment]
> 
> 
> It shouldn't matter as the build file will be overridden on the next compilation. Are you still able to build it ?

no sir, it did not build or open the menuconfig

**Comment by jonathanmuller** [comment]
Are you not able to because the missing file(s) make it break, or did not try ?
Also what if you just copy paste the menu-config and the code from github ?
