### ISSUE TITLE
why not able to connect to AP and errors while running the code in STA mode

### ISSUE THREAD

**Issue by kallu1294** [jonathanmuller/ESP32-gather-channel-state-information-CSI-#8]
Hi sir whenever i try  to connect any devices to esp32 in AP mode Why I'm not able to connect.?
![AP](https://user-images.githubusercontent.com/94892862/144792562-426f4af0-57c5-4dfd-93a0-0bd93d192b34.jpg)

And the below is for STA mode

![STA_](https://user-images.githubusercontent.com/94892862/144793057-ab6537d0-dadd-413b-83f1-9914712826d2.jpg)

**Comment by jonathanmuller** [comment]
Hi, 

Not sure if you have error in the compilation (as the tittle suggest) or while the app is running (as suggest the images) ?

In any case, are you able to connect to the AP using a smartphone/laptop/anything ?

**Comment by kallu1294** [comment]
> Hi,
> 
> Not sure if you have error in the compilation (as the tittle suggest) or while the app is running (as suggest the images) ?
> 
> In any case, are you able to connect to the AP using a smartphone/laptop/anything ?

sorry no I'm not able to connect any devices to esp32 in AP mode nor by smartphone /laptop or any other wireless devices


And why in STA mode it is showing like that may i know please.??

And how should i collect the CSI data from STA mode(only using single ESP32 board as STA).?

**Comment by jonathanmuller** [comment]
Do you even see the AP ? I guess yes
What's the name of the AP and what password are you using ?

**Comment by kallu1294** [comment]
> Do you even see the AP ? I guess yes What's the name of the AP and what password are you using ?

As shown in the above image i used SSID as esp32 and password as esp32pass which i changed in AP code

**Comment by jonathanmuller** [comment]
If you don't mind trying with the initial code (without any modifications), that way we can rule out things one after another
Also which version of esp-idf are you using ?
Also, are you able to make the idf AP/client example work ? (https://github.com/espressif/esp-idf/tree/master/examples/wifi/getting_started)

**Comment by kallu1294** [comment]
> If you don't mind trying with the initial code (without any modifications), that way we can rule out things one after another Also which version of esp-idf are you using ? Also, are you able to make the idf AP/client example work ? (https://github.com/espressif/esp-idf/tree/master/examples/wifi/getting_started)

Sorry sir for modifying and trying but before that i tried without modifying only but it shown same thing as it showing now and I'm using IDF_VER : V5.0 -dev

yes i tried that example softAP for that also it is showing same thing only I'm trying to connect my smartphone and laptop with esp32 in softAP mode 

But sir i need my esp32 should work in STA mode that's it. I'm using single board that is in STA mode and i want to connect that with my WIFI(router) and download the CSI data

**Comment by kallu1294** [comment]
Sir why I'm not able to connect to my esp32 to my wifi moudule in  station mode which is given in example ,because I'm using single ESP32 board is that the reason..??

**Comment by jonathanmuller** [comment]
I suspect the latest IDF (5+) to not work well with "old" wifi connection code, I also struggle to make it work on other projects.
If you only want to connect to an AP to extract the CSI then you could just use esp-idf examples to connect a STA to an AP, then use part of my code to display CSI, for example

**Comment by kallu1294** [comment]
> I suspect the latest IDF (5+) to not work well with "old" wifi connection code, I also struggle to make it work on other projects. If you only want to connect to an AP to extract the CSI then you could just use esp-idf examples to connect a STA to an AP, then use part of my code to display CSI, for example

Sir i want to download csi data into txt file is it possible..??
However your code for STA giving loop error inside the STA code like i shown in the above image.
And I'm not able to connect in AP mode from your code  :-(

**Comment by jonathanmuller** [comment]
I don't have time to dedicate to this right now, but if you manage to fix the problem I would be glad to review the PR.
As i said, try to use Espressif example from their main repo to have a working base, then you can add part of my code to plot CSI, for example.
